version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - database

  database:
    build:
      context: ./db
      dockerfile: Dockerfile
    networks:
      - app-network

  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
