version: '3.7'

services:
  backendred:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - database
  
  backendblue:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - database

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - database

  database:
    build:
      context: ./db
      dockerfile: Dockerfile
    networks:
      - app-network

  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
